*&---------------------------------------------------------------------*
*& Include zgw_tools_oo_sel - GW Tools Selection Screen
*&---------------------------------------------------------------------*
" Execution options (Magic Wand)
SELECTION-SCREEN BEGIN OF BLOCK bo WITH FRAME TITLE TEXT-mwt.

  SELECTION-SCREEN COMMENT /1(79) TEXT-cas.
  SELECTION-SCREEN ULINE.

  PARAMETERS:
    p_wipesm RADIOBUTTON GROUP ro DEFAULT 'X',
    p_unamem TYPE syuname LOWER CASE DEFAULT sy-uname MATCHCODE OBJECT user_comp.

  SELECTION-SCREEN SKIP.
  PARAMETERS:
    p_wipeme RADIOBUTTON GROUP ro.
  SELECT-OPTIONS: serv_id FOR /iwfnd/i_med_srh-srv_identifier NO INTERVALS.

  SELECTION-SCREEN SKIP.
  PARAMETERS:
    p_wipem4 RADIOBUTTON GROUP ro,
    p_srvgrp TYPE /iwbep/v4_med_group_id NO-DISPLAY,
    p_srvid4 TYPE /iwbep/i_v4_msrv-service_id,
    p_srvrep TYPE /iwbep/v4_med_repository_id NO-DISPLAY,
    p_srvve4 TYPE /iwbep/i_v4_msrv-service_version NO-DISPLAY.

  SELECTION-SCREEN SKIP.
  SELECTION-SCREEN COMMENT /1(79) TEXT-flp.
  SELECTION-SCREEN ULINE.

  PARAMETERS:
    p_index RADIOBUTTON GROUP ro,
    p_repo  TYPE /ui5/ui5_repository_ui.
  SELECTION-SCREEN SKIP.
  PARAMETERS:
    p_idxbck RADIOBUTTON GROUP ro,
    p_wipesg RADIOBUTTON GROUP ro.


  SELECTION-SCREEN SKIP.
  SELECTION-SCREEN COMMENT /1(50) TEXT-sic.
  SELECTION-SCREEN ULINE.
  PARAMETERS:
    p_icfact RADIOBUTTON GROUP ro,
    p_icfina RADIOBUTTON GROUP ro,
    p_odui5o AS CHECKBOX.

SELECTION-SCREEN END OF BLOCK bo.

SELECTION-SCREEN BEGIN OF BLOCK bg WITH FRAME TITLE TEXT-gid.
  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS: p_iedm  TYPE c LENGTH 36 LOWER CASE.
    SELECTION-SCREEN PUSHBUTTON 38(12) TEXT-bgi USER-COMMAND gin.
    PARAMETERS: p_oraw  TYPE sysuuid_c32.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS: p_iraw  TYPE sysuuid_c32.
    SELECTION-SCREEN PUSHBUTTON 34(12) TEXT-bgo USER-COMMAND gou.
    PARAMETERS: p_oedm  TYPE c LENGTH 36 LOWER CASE.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bg.


" Help texts
SELECTION-SCREEN BEGIN OF BLOCK bh WITH FRAME TITLE ht.
  SELECTION-SCREEN COMMENT /1(79) hl1.
  SELECTION-SCREEN COMMENT /1(79) hl2.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 3(4) ico_nono.
    SELECTION-SCREEN COMMENT 7(73) h21.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN COMMENT /1(79) hl3.
  SELECTION-SCREEN COMMENT /1(79) hl4.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 3(4) ico_hey.
    SELECTION-SCREEN COMMENT 7(73) hl_hey.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN COMMENT /1(79) hl5.
  SELECTION-SCREEN COMMENT /1(79) hl6.
  SELECTION-SCREEN COMMENT /2(78) hl7.
  SELECTION-SCREEN COMMENT /1(79) hl8.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 3(4) ico_warn.
    SELECTION-SCREEN COMMENT 7(73) hl9.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN COMMENT /1(79) h10.
  SELECTION-SCREEN COMMENT /3(77) h11.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 3(4) ico_men.
    SELECTION-SCREEN COMMENT 7(73) hl_men.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN COMMENT /1(79) hl_bctx1.
  SELECTION-SCREEN COMMENT /3(79) hl_bctx2.

SELECTION-SCREEN END OF BLOCK bh.

" Help for browser cache
SELECTION-SCREEN BEGIN OF BLOCK bbc WITH FRAME TITLE tbc.
  SELECTION-SCREEN COMMENT /1(79) bc1.
  SELECTION-SCREEN COMMENT /1(79) bc2.
  SELECTION-SCREEN COMMENT /1(79) bc3.
  SELECTION-SCREEN COMMENT /1(79) bc4.
SELECTION-SCREEN END OF BLOCK bbc.
